/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif

using namespace Tango;

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_tango_client(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_tango_client(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_tango_client(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


#include "DeviceProxy.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_new_DeviceProxy__SWIG_0(void * jarg1, void * jarg2) {
  void * jresult ;
  string *arg1 = 0 ;
  CORBA::ORB *arg2 = (CORBA::ORB *) 0 ;
  DeviceProxy *result = 0 ;
  
  arg1 = (string *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  arg2 = (CORBA::ORB *)jarg2; 
  result = (DeviceProxy *)new DeviceProxy(*arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DeviceProxy__SWIG_1(void * jarg1) {
  void * jresult ;
  string *arg1 = 0 ;
  DeviceProxy *result = 0 ;
  
  arg1 = (string *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  result = (DeviceProxy *)new DeviceProxy(*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DeviceProxy__SWIG_2(char * jarg1, void * jarg2) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  CORBA::ORB *arg2 = (CORBA::ORB *) 0 ;
  DeviceProxy *result = 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (CORBA::ORB *)jarg2; 
  result = (DeviceProxy *)new DeviceProxy((char const *)arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DeviceProxy__SWIG_3(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  DeviceProxy *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (DeviceProxy *)new DeviceProxy((char const *)arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DeviceProxy__SWIG_4(void * jarg1, unsigned int jarg2, void * jarg3) {
  void * jresult ;
  string *arg1 = 0 ;
  bool arg2 ;
  CORBA::ORB *arg3 = (CORBA::ORB *) 0 ;
  DeviceProxy *result = 0 ;
  
  arg1 = (string *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  arg2 = jarg2 ? true : false; 
  arg3 = (CORBA::ORB *)jarg3; 
  result = (DeviceProxy *)new DeviceProxy(*arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DeviceProxy__SWIG_5(void * jarg1, unsigned int jarg2) {
  void * jresult ;
  string *arg1 = 0 ;
  bool arg2 ;
  DeviceProxy *result = 0 ;
  
  arg1 = (string *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  arg2 = jarg2 ? true : false; 
  result = (DeviceProxy *)new DeviceProxy(*arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DeviceProxy__SWIG_6(char * jarg1, unsigned int jarg2, void * jarg3) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  bool arg2 ;
  CORBA::ORB *arg3 = (CORBA::ORB *) 0 ;
  DeviceProxy *result = 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = jarg2 ? true : false; 
  arg3 = (CORBA::ORB *)jarg3; 
  result = (DeviceProxy *)new DeviceProxy((char const *)arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DeviceProxy__SWIG_7(char * jarg1, unsigned int jarg2) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  bool arg2 ;
  DeviceProxy *result = 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = jarg2 ? true : false; 
  result = (DeviceProxy *)new DeviceProxy((char const *)arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DeviceProxy__SWIG_8(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = 0 ;
  DeviceProxy *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DeviceProxy const & type is null", 0);
    return 0;
  } 
  result = (DeviceProxy *)new DeviceProxy((DeviceProxy const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_DeviceProxy(void * jarg1) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_DeviceProxy__SWIG_9() {
  void * jresult ;
  DeviceProxy *result = 0 ;
  
  result = (DeviceProxy *)new DeviceProxy();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_info(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DeviceInfo *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (DeviceInfo *) &(arg1)->info();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_state(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DevState result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (arg1)->state();
  jresult = new DevState((const DevState &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_status(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (arg1)->status();
  jresult = new string((const string &)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_ping(void * jarg1) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (int)(arg1)->ping();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_black_box(void * jarg1, int jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  vector< string > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  result = (vector< string > *)(arg1)->black_box(arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_name(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (arg1)->name();
  jresult = new string((const string &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_adm_name(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (arg1)->adm_name();
  jresult = new string((const string &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_dev_name(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (arg1)->dev_name();
  jresult = new string((const string &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_description(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (arg1)->description();
  jresult = new string((const string &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_alias(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (arg1)->alias();
  jresult = new string((const string &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_import_info(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DbDevImportInfo result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (arg1)->import_info();
  jresult = new DbDevImportInfo((const DbDevImportInfo &)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_get_tango_lib_version(void * jarg1) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (int)(arg1)->get_tango_lib_version();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_command_query(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string arg2 ;
  string *argp2 ;
  CommandInfo result;
  
  arg1 = (DeviceProxy *)jarg1; 
  argp2 = (string *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null string", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (arg1)->command_query(arg2);
  jresult = new CommandInfo((const CommandInfo &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_command_list_query(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  CommandInfoList *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (CommandInfoList *)(arg1)->command_list_query();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_command_list(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (vector< string > *)(arg1)->get_command_list();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_command_config__SWIG_0(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  CommandInfo result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  result = (arg1)->get_command_config((string const &)*arg2);
  jresult = new CommandInfo((const CommandInfo &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_command_config__SWIG_1(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *arg2 = 0 ;
  CommandInfoList *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< string > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return 0;
  } 
  result = (CommandInfoList *)(arg1)->get_command_config(*arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_command_history__SWIG_0(void * jarg1, void * jarg2, int jarg3) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  int arg3 ;
  vector< DeviceDataHistory > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  arg3 = (int)jarg3; 
  result = (vector< DeviceDataHistory > *)(arg1)->command_history(*arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_command_history__SWIG_1(void * jarg1, char * jarg2, int jarg3) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  vector< DeviceDataHistory > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int)jarg3; 
  result = (vector< DeviceDataHistory > *)(arg1)->command_history((char const *)arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_attribute_query(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string arg2 ;
  string *argp2 ;
  AttributeInfoEx result;
  
  arg1 = (DeviceProxy *)jarg1; 
  argp2 = (string *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null string", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (arg1)->attribute_query(arg2);
  jresult = new AttributeInfoEx((const AttributeInfoEx &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_attribute_list_query(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  AttributeInfoList *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (AttributeInfoList *)(arg1)->attribute_list_query();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_attribute_list_query_ex(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  AttributeInfoListEx *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (AttributeInfoListEx *)(arg1)->attribute_list_query_ex();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_attribute_list(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (vector< string > *)(arg1)->get_attribute_list();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_attribute_config__SWIG_0(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *arg2 = 0 ;
  AttributeInfoList *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< string > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return 0;
  } 
  result = (AttributeInfoList *)(arg1)->get_attribute_config(*arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_attribute_config_ex(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *arg2 = 0 ;
  AttributeInfoListEx *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< string > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return 0;
  } 
  result = (AttributeInfoListEx *)(arg1)->get_attribute_config_ex(*arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_attribute_config__SWIG_1(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  AttributeInfoEx result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  result = (arg1)->get_attribute_config((string const &)*arg2);
  jresult = new AttributeInfoEx((const AttributeInfoEx &)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_set_attribute_config__SWIG_0(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  AttributeInfoList *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (AttributeInfoList *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "AttributeInfoList & type is null", 0);
    return ;
  } 
  (arg1)->set_attribute_config(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_set_attribute_config__SWIG_1(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  AttributeInfoListEx *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (AttributeInfoListEx *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "AttributeInfoListEx & type is null", 0);
    return ;
  } 
  (arg1)->set_attribute_config(*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_read_attributes(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *arg2 = 0 ;
  vector< DeviceAttribute > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< string > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return 0;
  } 
  result = (vector< DeviceAttribute > *)(arg1)->read_attributes(*arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_read_attribute__SWIG_0(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  DeviceAttribute result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  result = (arg1)->read_attribute(*arg2);
  jresult = new DeviceAttribute((const DeviceAttribute &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_read_attribute__SWIG_1(void * jarg1, char * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  DeviceAttribute result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (arg1)->read_attribute((char const *)arg2);
  jresult = new DeviceAttribute((const DeviceAttribute &)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_write_attributes(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< DeviceAttribute > *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< DeviceAttribute > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< DeviceAttribute > & type is null", 0);
    return ;
  } 
  (arg1)->write_attributes(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_write_attribute(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DeviceAttribute *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (DeviceAttribute *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DeviceAttribute & type is null", 0);
    return ;
  } 
  (arg1)->write_attribute(*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_write_read_attribute(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DeviceAttribute *arg2 = 0 ;
  DeviceAttribute result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (DeviceAttribute *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DeviceAttribute & type is null", 0);
    return 0;
  } 
  result = (arg1)->write_read_attribute(*arg2);
  jresult = new DeviceAttribute((const DeviceAttribute &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_write_read_attributes(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< DeviceAttribute > *arg2 = 0 ;
  vector< string > *arg3 = 0 ;
  vector< DeviceAttribute > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< DeviceAttribute > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< DeviceAttribute > & type is null", 0);
    return 0;
  } 
  arg3 = (vector< string > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return 0;
  } 
  result = (vector< DeviceAttribute > *)(arg1)->write_read_attributes(*arg2,*arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_attribute_history__SWIG_0(void * jarg1, void * jarg2, int jarg3) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  int arg3 ;
  vector< DeviceAttributeHistory > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  arg3 = (int)jarg3; 
  result = (vector< DeviceAttributeHistory > *)(arg1)->attribute_history(*arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_attribute_history__SWIG_1(void * jarg1, char * jarg2, int jarg3) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  vector< DeviceAttributeHistory > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int)jarg3; 
  result = (vector< DeviceAttributeHistory > *)(arg1)->attribute_history((char const *)arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_pipe_config__SWIG_0(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *arg2 = 0 ;
  PipeInfoList *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< string > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return 0;
  } 
  result = (PipeInfoList *)(arg1)->get_pipe_config(*arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_pipe_config__SWIG_1(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  PipeInfo result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  result = (arg1)->get_pipe_config((string const &)*arg2);
  jresult = new PipeInfo((const PipeInfo &)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_set_pipe_config(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  PipeInfoList *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (PipeInfoList *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PipeInfoList & type is null", 0);
    return ;
  } 
  (arg1)->set_pipe_config(*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_pipe_list(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (vector< string > *)(arg1)->get_pipe_list();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_read_pipe(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  DevicePipe result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  result = (arg1)->read_pipe((string const &)*arg2);
  jresult = new DevicePipe((const DevicePipe &)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_write_pipe(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DevicePipe *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (DevicePipe *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DevicePipe & type is null", 0);
    return ;
  } 
  (arg1)->write_pipe(*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_write_read_pipe(void * jarg1, void * jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DevicePipe *arg2 = 0 ;
  DevicePipe result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (DevicePipe *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DevicePipe & type is null", 0);
    return 0;
  } 
  result = (arg1)->write_read_pipe(*arg2);
  jresult = new DevicePipe((const DevicePipe &)result); 
  return jresult;
}


SWIGEXPORT long SWIGSTDCALL CSharp_DeviceProxy_read_attribute_asynch__SWIG_0(void * jarg1, void * jarg2) {
  long jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  long result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  result = (long)(arg1)->read_attribute_asynch(*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT long SWIGSTDCALL CSharp_DeviceProxy_read_attribute_asynch__SWIG_1(void * jarg1, char * jarg2) {
  long jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  long result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (long)(arg1)->read_attribute_asynch((char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT long SWIGSTDCALL CSharp_DeviceProxy_read_attributes_asynch__SWIG_0(void * jarg1, void * jarg2) {
  long jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *arg2 = 0 ;
  long result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< string > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return 0;
  } 
  result = (long)(arg1)->read_attributes_asynch(*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_read_attributes_reply__SWIG_0(void * jarg1, long jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  long arg2 ;
  vector< DeviceAttribute > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (long)jarg2; 
  result = (vector< DeviceAttribute > *)(arg1)->read_attributes_reply(arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_read_attributes_reply__SWIG_1(void * jarg1, long jarg2, long jarg3) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  long arg2 ;
  long arg3 ;
  vector< DeviceAttribute > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (long)jarg2; 
  arg3 = (long)jarg3; 
  result = (vector< DeviceAttribute > *)(arg1)->read_attributes_reply(arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_read_attribute_reply__SWIG_0(void * jarg1, long jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  long arg2 ;
  DeviceAttribute *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (long)jarg2; 
  result = (DeviceAttribute *)(arg1)->read_attribute_reply(arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_read_attribute_reply__SWIG_1(void * jarg1, long jarg2, long jarg3) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  long arg2 ;
  long arg3 ;
  DeviceAttribute *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (long)jarg2; 
  arg3 = (long)jarg3; 
  result = (DeviceAttribute *)(arg1)->read_attribute_reply(arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT long SWIGSTDCALL CSharp_DeviceProxy_write_attribute_asynch__SWIG_0(void * jarg1, void * jarg2) {
  long jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DeviceAttribute *arg2 = 0 ;
  long result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (DeviceAttribute *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DeviceAttribute & type is null", 0);
    return 0;
  } 
  result = (long)(arg1)->write_attribute_asynch(*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT long SWIGSTDCALL CSharp_DeviceProxy_write_attributes_asynch__SWIG_0(void * jarg1, void * jarg2) {
  long jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< DeviceAttribute > *arg2 = 0 ;
  long result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< DeviceAttribute > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< DeviceAttribute > & type is null", 0);
    return 0;
  } 
  result = (long)(arg1)->write_attributes_asynch(*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_write_attribute_reply__SWIG_0(void * jarg1, long jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  long arg2 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (long)jarg2; 
  (arg1)->write_attribute_reply(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_write_attribute_reply__SWIG_1(void * jarg1, long jarg2, long jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  long arg2 ;
  long arg3 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (long)jarg2; 
  arg3 = (long)jarg3; 
  (arg1)->write_attribute_reply(arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_write_attributes_reply__SWIG_0(void * jarg1, long jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  long arg2 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (long)jarg2; 
  (arg1)->write_attributes_reply(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_write_attributes_reply__SWIG_1(void * jarg1, long jarg2, long jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  long arg2 ;
  long arg3 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (long)jarg2; 
  arg3 = (long)jarg3; 
  (arg1)->write_attributes_reply(arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_read_attribute_asynch__SWIG_2(void * jarg1, char * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  CallBack *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (CallBack *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "CallBack & type is null", 0);
    return ;
  } 
  (arg1)->read_attribute_asynch((char const *)arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_read_attribute_asynch__SWIG_3(void * jarg1, void * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  CallBack *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return ;
  } 
  arg3 = (CallBack *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "CallBack & type is null", 0);
    return ;
  } 
  (arg1)->read_attribute_asynch(*arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_read_attributes_asynch__SWIG_1(void * jarg1, void * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *arg2 = 0 ;
  CallBack *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< string > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return ;
  } 
  arg3 = (CallBack *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "CallBack & type is null", 0);
    return ;
  } 
  (arg1)->read_attributes_asynch(*arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_write_attribute_asynch__SWIG_1(void * jarg1, void * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DeviceAttribute *arg2 = 0 ;
  CallBack *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (DeviceAttribute *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DeviceAttribute & type is null", 0);
    return ;
  } 
  arg3 = (CallBack *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "CallBack & type is null", 0);
    return ;
  } 
  (arg1)->write_attribute_asynch(*arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_write_attributes_asynch__SWIG_1(void * jarg1, void * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< DeviceAttribute > *arg2 = 0 ;
  CallBack *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< DeviceAttribute > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< DeviceAttribute > & type is null", 0);
    return ;
  } 
  arg3 = (CallBack *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "CallBack & type is null", 0);
    return ;
  } 
  (arg1)->write_attributes_asynch(*arg2,*arg3);
}


SWIGEXPORT long SWIGSTDCALL CSharp_DeviceProxy_pending_asynch_call(void * jarg1, void * jarg2) {
  long jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  asyn_req_type arg2 ;
  asyn_req_type *argp2 ;
  long result;
  
  arg1 = (DeviceProxy *)jarg1; 
  argp2 = (asyn_req_type *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null asyn_req_type", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (long)(arg1)->pending_asynch_call(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DeviceProxy_is_command_polled__SWIG_0(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  bool result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  result = (bool)(arg1)->is_command_polled(*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DeviceProxy_is_command_polled__SWIG_1(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (bool)(arg1)->is_command_polled((char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DeviceProxy_is_attribute_polled__SWIG_0(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  bool result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  result = (bool)(arg1)->is_attribute_polled(*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DeviceProxy_is_attribute_polled__SWIG_1(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (bool)(arg1)->is_attribute_polled((char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_get_command_poll_period__SWIG_0(void * jarg1, void * jarg2) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  result = (int)(arg1)->get_command_poll_period(*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_get_command_poll_period__SWIG_1(void * jarg1, char * jarg2) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)(arg1)->get_command_poll_period((char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_get_attribute_poll_period__SWIG_0(void * jarg1, void * jarg2) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return 0;
  } 
  result = (int)(arg1)->get_attribute_poll_period(*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_get_attribute_poll_period__SWIG_1(void * jarg1, char * jarg2) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)(arg1)->get_attribute_poll_period((char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_polling_status(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (vector< string > *)(arg1)->polling_status();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_poll_command__SWIG_0(void * jarg1, void * jarg2, int jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  int arg3 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return ;
  } 
  arg3 = (int)jarg3; 
  (arg1)->poll_command(*arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_poll_command__SWIG_1(void * jarg1, char * jarg2, int jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int)jarg3; 
  (arg1)->poll_command((char const *)arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_poll_attribute__SWIG_0(void * jarg1, void * jarg2, int jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  int arg3 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return ;
  } 
  arg3 = (int)jarg3; 
  (arg1)->poll_attribute(*arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_poll_attribute__SWIG_1(void * jarg1, char * jarg2, int jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int)jarg3; 
  (arg1)->poll_attribute((char const *)arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_stop_poll_command__SWIG_0(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return ;
  } 
  (arg1)->stop_poll_command(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_stop_poll_command__SWIG_1(void * jarg1, char * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  (arg1)->stop_poll_command((char const *)arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_stop_poll_attribute__SWIG_0(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return ;
  } 
  (arg1)->stop_poll_attribute(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_stop_poll_attribute__SWIG_1(void * jarg1, char * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  (arg1)->stop_poll_attribute((char const *)arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_0(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  EventType arg3 ;
  CallBack *arg4 = (CallBack *) 0 ;
  EventType *argp3 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  argp3 = (EventType *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (CallBack *)jarg4; 
  result = (int)(arg1)->subscribe_event((string const &)*arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_1(void * jarg1, void * jarg2, void * jarg3, void * jarg4, unsigned int jarg5) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  EventType arg3 ;
  CallBack *arg4 = (CallBack *) 0 ;
  bool arg5 ;
  EventType *argp3 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  argp3 = (EventType *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (CallBack *)jarg4; 
  arg5 = jarg5 ? true : false; 
  result = (int)(arg1)->subscribe_event((string const &)*arg2,arg3,arg4,arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_2(void * jarg1, void * jarg2, void * jarg3, int jarg4, unsigned int jarg5) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  EventType arg3 ;
  int arg4 ;
  bool arg5 ;
  EventType *argp3 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  argp3 = (EventType *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (int)jarg4; 
  arg5 = jarg5 ? true : false; 
  result = (int)(arg1)->subscribe_event((string const &)*arg2,arg3,arg4,arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_3(void * jarg1, void * jarg2, void * jarg3, int jarg4) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  EventType arg3 ;
  int arg4 ;
  EventType *argp3 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  argp3 = (EventType *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (int)jarg4; 
  result = (int)(arg1)->subscribe_event((string const &)*arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_4(void * jarg1, void * jarg2, void * jarg3, unsigned int jarg4) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  EventType arg2 ;
  CallBack *arg3 = (CallBack *) 0 ;
  bool arg4 ;
  EventType *argp2 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  argp2 = (EventType *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (CallBack *)jarg3; 
  arg4 = jarg4 ? true : false; 
  result = (int)(arg1)->subscribe_event(arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_5(void * jarg1, void * jarg2, void * jarg3) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  EventType arg2 ;
  CallBack *arg3 = (CallBack *) 0 ;
  EventType *argp2 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  argp2 = (EventType *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (CallBack *)jarg3; 
  result = (int)(arg1)->subscribe_event(arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_6(void * jarg1, void * jarg2, int jarg3, unsigned int jarg4) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  EventType arg2 ;
  int arg3 ;
  bool arg4 ;
  EventType *argp2 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  argp2 = (EventType *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (int)jarg3; 
  arg4 = jarg4 ? true : false; 
  result = (int)(arg1)->subscribe_event(arg2,arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_7(void * jarg1, void * jarg2, int jarg3) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  EventType arg2 ;
  int arg3 ;
  EventType *argp2 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  argp2 = (EventType *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (int)jarg3; 
  result = (int)(arg1)->subscribe_event(arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_unsubscribe_event(void * jarg1, int jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  (arg1)->unsubscribe_event(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_get_events__SWIG_0(void * jarg1, int jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  CallBack *arg3 = (CallBack *) 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (CallBack *)jarg3; 
  (arg1)->get_events(arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_get_events__SWIG_1(void * jarg1, int jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  EventDataList *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (EventDataList *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "EventDataList & type is null", 0);
    return ;
  } 
  (arg1)->get_events(arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_get_events__SWIG_2(void * jarg1, int jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  AttrConfEventDataList *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (AttrConfEventDataList *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "AttrConfEventDataList & type is null", 0);
    return ;
  } 
  (arg1)->get_events(arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_get_events__SWIG_3(void * jarg1, int jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  DataReadyEventDataList *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (DataReadyEventDataList *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DataReadyEventDataList & type is null", 0);
    return ;
  } 
  (arg1)->get_events(arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_get_events__SWIG_4(void * jarg1, int jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  DevIntrChangeEventDataList *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (DevIntrChangeEventDataList *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DevIntrChangeEventDataList & type is null", 0);
    return ;
  } 
  (arg1)->get_events(arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_get_events__SWIG_5(void * jarg1, int jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  PipeEventDataList *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (PipeEventDataList *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "PipeEventDataList & type is null", 0);
    return ;
  } 
  (arg1)->get_events(arg2,*arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_event_queue_size(void * jarg1, int jarg2) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)(arg1)->event_queue_size(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_last_event_date(void * jarg1, int jarg2) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  TimeVal result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->get_last_event_date(arg2);
  jresult = new TimeVal((const TimeVal &)result); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DeviceProxy_is_event_queue_empty(void * jarg1, int jarg2) {
  unsigned int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  bool result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  result = (bool)(arg1)->is_event_queue_empty(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_get_property__SWIG_0(void * jarg1, void * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  DbData *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return ;
  } 
  arg3 = (DbData *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DbData & type is null", 0);
    return ;
  } 
  (arg1)->get_property(*arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_get_property__SWIG_1(void * jarg1, void * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *arg2 = 0 ;
  DbData *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< string > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return ;
  } 
  arg3 = (DbData *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DbData & type is null", 0);
    return ;
  } 
  (arg1)->get_property(*arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_get_property__SWIG_2(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DbData *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (DbData *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DbData & type is null", 0);
    return ;
  } 
  (arg1)->get_property(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_put_property(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DbData *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (DbData *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DbData & type is null", 0);
    return ;
  } 
  (arg1)->put_property(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_delete_property__SWIG_0(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return ;
  } 
  (arg1)->delete_property(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_delete_property__SWIG_1(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  vector< string > *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (vector< string > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return ;
  } 
  (arg1)->delete_property(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_delete_property__SWIG_2(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DbData *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (DbData *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DbData & type is null", 0);
    return ;
  } 
  (arg1)->delete_property(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_get_property_list(void * jarg1, void * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  vector< string > *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return ;
  } 
  arg3 = (vector< string > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > & type is null", 0);
    return ;
  } 
  (arg1)->get_property_list((string const &)*arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_lock___SWIG_0(void * jarg1, int jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  int arg2 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (int)jarg2; 
  (arg1)->lock(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_lock___SWIG_1(void * jarg1) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  (arg1)->lock();
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_unlock__SWIG_0(void * jarg1, unsigned int jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  bool arg2 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->unlock(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_unlock__SWIG_1(void * jarg1) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  (arg1)->unlock();
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_locking_status(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (arg1)->locking_status();
  jresult = new string((const string &)result); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DeviceProxy_is_locked(void * jarg1) {
  unsigned int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  bool result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (bool)(arg1)->is_locked();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DeviceProxy_is_locked_by_me(void * jarg1) {
  unsigned int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  bool result;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (bool)(arg1)->is_locked_by_me();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DeviceProxy_get_locker(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  LockerInfo *arg2 = 0 ;
  bool result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (LockerInfo *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "LockerInfo & type is null", 0);
    return 0;
  } 
  result = (bool)(arg1)->get_locker(*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_parse_name(void * jarg1, void * jarg2) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return ;
  } 
  (arg1)->parse_name(*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_device_db(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  Database *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (Database *)(arg1)->get_device_db();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DeviceProxy_get_adm_device(void * jarg1) {
  void * jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  DeviceProxy *result = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  result = (DeviceProxy *)(arg1)->get_adm_device();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_read_attribute__SWIG_2(void * jarg1, void * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  AttributeValue_4 **arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return ;
  } 
  arg3 = (AttributeValue_4 **)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "AttributeValue_4 *& type is null", 0);
    return ;
  } 
  (arg1)->read_attribute((string const &)*arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_read_attribute__SWIG_3(void * jarg1, void * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  AttributeValue_5 **arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return ;
  } 
  arg3 = (AttributeValue_5 **)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "AttributeValue_5 *& type is null", 0);
    return ;
  } 
  (arg1)->read_attribute((string const &)*arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_read_attribute__SWIG_4(void * jarg1, char * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  char *arg2 = (char *) 0 ;
  DeviceAttribute *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (DeviceAttribute *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DeviceAttribute & type is null", 0);
    return ;
  } 
  (arg1)->read_attribute((char const *)arg2,*arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DeviceProxy_read_attribute__SWIG_5(void * jarg1, void * jarg2, void * jarg3) {
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  DeviceAttribute *arg3 = 0 ;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string & type is null", 0);
    return ;
  } 
  arg3 = (DeviceAttribute *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "DeviceAttribute & type is null", 0);
    return ;
  } 
  (arg1)->read_attribute(*arg2,*arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_8(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  EventType arg3 ;
  CallBack *arg4 = (CallBack *) 0 ;
  vector< string > *arg5 = 0 ;
  EventType *argp3 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  argp3 = (EventType *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (CallBack *)jarg4; 
  arg5 = (vector< string > *)jarg5;
  if (!arg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > const & type is null", 0);
    return 0;
  } 
  result = (int)(arg1)->subscribe_event((string const &)*arg2,arg3,arg4,(vector< string > const &)*arg5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_9(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5, unsigned int jarg6) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  EventType arg3 ;
  CallBack *arg4 = (CallBack *) 0 ;
  vector< string > *arg5 = 0 ;
  bool arg6 ;
  EventType *argp3 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  argp3 = (EventType *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (CallBack *)jarg4; 
  arg5 = (vector< string > *)jarg5;
  if (!arg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > const & type is null", 0);
    return 0;
  } 
  arg6 = jarg6 ? true : false; 
  result = (int)(arg1)->subscribe_event((string const &)*arg2,arg3,arg4,(vector< string > const &)*arg5,arg6);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_10(void * jarg1, void * jarg2, void * jarg3, int jarg4, void * jarg5, unsigned int jarg6) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  EventType arg3 ;
  int arg4 ;
  vector< string > *arg5 = 0 ;
  bool arg6 ;
  EventType *argp3 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  argp3 = (EventType *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (int)jarg4; 
  arg5 = (vector< string > *)jarg5;
  if (!arg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > const & type is null", 0);
    return 0;
  } 
  arg6 = jarg6 ? true : false; 
  result = (int)(arg1)->subscribe_event((string const &)*arg2,arg3,arg4,(vector< string > const &)*arg5,arg6);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DeviceProxy_subscribe_event__SWIG_11(void * jarg1, void * jarg2, void * jarg3, int jarg4, void * jarg5) {
  int jresult ;
  DeviceProxy *arg1 = (DeviceProxy *) 0 ;
  string *arg2 = 0 ;
  EventType arg3 ;
  int arg4 ;
  vector< string > *arg5 = 0 ;
  EventType *argp3 ;
  int result;
  
  arg1 = (DeviceProxy *)jarg1; 
  arg2 = (string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "string const & type is null", 0);
    return 0;
  } 
  argp3 = (EventType *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null EventType", 0);
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (int)jarg4; 
  arg5 = (vector< string > *)jarg5;
  if (!arg5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "vector< string > const & type is null", 0);
    return 0;
  } 
  result = (int)(arg1)->subscribe_event((string const &)*arg2,arg3,arg4,(vector< string > const &)*arg5);
  jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

